// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wejynbgsvvmfxwuexugf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlanluYmdzdnZtZnh3dWV4dWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NTMyMjcsImV4cCI6MjA1NTEyOTIyN30.vK6A8ZaKWlNVR-fGf5p7IqwqljZ0oqkK_gl6yqG6iPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);